# Generated by Django 4.2.30 on 2026-09-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegecourse',
            name='intake_capacity',
        ),
        migrations.AddField(
            model_name='college',
            name='latitude',
            field=models.FloatField(default=23.0225),
        ),
        migrations.AddField(
            model_name='college',
            name='longitude',
            field=models.FloatField(default=72.5714),
        ),
        migrations.AddField(
            model_name='datareport',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datareport',
            name='suggested_correction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datareport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='latitude',
            field=models.FloatField(default=23.0225),
        ),
        migrations.AddField(
            model_name='hostel',
            name='longitude',
            field=models.FloatField(default=72.5714),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='annual_fee',
            field=models.CharField(default='Fee information not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='annual_fee_approx',
            field=models.CharField(default='Fee information not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='distance_to_top_colleges',
            field=models.TextField(help_text='e.g. 0.8 km from college'),
        ),
    ]
