# Generated by Django 4.2.30 on 2026-09-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_collegecourse_intake_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='college',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='institution_category',
            field=models.CharField(choices=[('Engineering', 'Engineering & Technology'), ('Commerce', 'Commerce & Business'), ('Science', 'Science & Research'), ('Arts', 'Arts & Humanities'), ('Management', 'Management & BBA'), ('Pharmacy', 'Pharmacy'), ('Law', 'Law & Legal Studies'), ('Computer Applications', 'Computer Applications (BCA/MCA)'), ('Medicine', 'Medicine & Allied Health'), ('Polytechnic', 'Diploma Polytechnic'), ('Architecture', 'Architecture & Planning'), ('Design', 'Design & Fine Arts'), ('Other', 'Other Recognized Higher Education')], db_index=True, default='Engineering', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('needs_review', 'Needs Review')], db_index=True, default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='college',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Grant-in-Aid', 'Grant-in-Aid'), ('Private', 'Private'), ('Self-Finance', 'Self-Finance'), ('University Department', 'University Department'), ('Constituent', 'Constituent College')], db_index=True, default='Government', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='college',
            unique_together={('name', 'city')},
        ),
    ]
