# Generated by Django 4.2.30 on 2026-09-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_college_options_college_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='hostel',
            name='accommodation_type',
            field=models.CharField(choices=[('Hostel', 'Student Hostel'), ('PG', 'Paying Guest (PG)'), ('Chhatralaya', 'Samaj Chhatralaya'), ('Student Residence', 'Student Co-Living Residence')], db_index=True, default='Hostel', max_length=50),
        ),
        migrations.AddField(
            model_name='hostel',
            name='availability_status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='hostel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='fee_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='fee_type',
            field=models.CharField(default='Yearly / Monthly', max_length=50),
        ),
        migrations.AddField(
            model_name='hostel',
            name='monthly_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('needs_review', 'Needs Review')], db_index=True, default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Co-Ed', 'Co-Ed')], db_index=True, default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('Government', 'Government Hostel'), ('University', 'University Hostel'), ('College', 'College Campus Hostel'), ('Trust/Community', 'Trust / Samaj Hostel'), ('Private', 'Private Hostel'), ('Student PG', 'Student PG'), ('Co-living', 'Co-Living Space')], db_index=True, default='Government', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='hostel',
            unique_together={('name', 'city')},
        ),
    ]
