# Generated by Django 4.2.30 on 2026-09-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hostel_options_hostel_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='location_last_verified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='college',
            name='location_source',
            field=models.CharField(default='Verified Address Coordinates', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='place_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='location_last_verified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='location_source',
            field=models.CharField(default='Verified Address Coordinates', max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='place_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='CollegeHostelDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.IntegerField(blank=True, help_text='Precise road distance in meters', null=True)),
                ('distance_km', models.FloatField(blank=True, help_text='Calculated road distance in kilometers', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Approximate travel time in seconds', null=True)),
                ('duration_text', models.CharField(blank=True, help_text='e.g. 6 mins', max_length=50, null=True)),
                ('provider', models.CharField(choices=[('google_routes', 'Google Maps Platform Routes API'), ('haversine', 'Haversine Geographic Calculator'), ('manual', 'Manual Admin Verified')], default='google_routes', max_length=50)),
                ('status', models.CharField(choices=[('verified', 'Verified Road Distance'), ('haversine_fallback', 'Haversine Fallback'), ('unavailable', 'Distance Unavailable')], default='verified', max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_distances', to='api.college')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_distances', to='api.hostel')),
            ],
            options={
                'ordering': ['distance_meters'],
                'unique_together': {('college', 'hostel')},
            },
        ),
    ]
